### ISSUE TITLE
Bootstrap menu on mobile with slide up/down animation

### ISSUE THREAD

**Issue by ronaldaug** [vadikom/smartmenus#102] opened 2019-12-05 04:26 UTC
How can I add Bootstrap dropdown with slide up/down animation (In mobile)?
In demo page, it seems it's not a slide up/down animation.

<img width="300" src="https://user-images.githubusercontent.com/33022876/70204096-a5373200-174d-11ea-9a81-4c7328b86db4.gif">

Btw,
This [free download](https://www.smartmenus.org/download/) button here isn't working. It has an PHP error.

**Comment by vadikom** [comment] 2019-12-05 14:25
Yep, it is done like that because Bootstrap's default behavior is to not use an animation so I wanted to comply.

As far as I can see, you are working with a Bootstrap 3 demo so you would need something like this (note the `data-sm-options` attribute in the HTML structure):

```html
<ul class="nav navbar-nav" data-sm-options="{ collapsibleShowFunction: function($ul, complete) { $ul.slideDown(200, complete); }, collapsibleHideFunction: function($ul, complete) { this.$root.off('hide.smapi'); $ul.slideUp(200, function() { $ul.parent().removeClass('open'); complete(); }); } }"> ...
```

<br/>

For Bootstrap 4, you would need something like this instead (in addition you would need to make sure the full jQuery version is used on your pages because by default they use the "slim" version which doesn't support animations):

```html
<ul class="nav navbar-nav" data-sm-options="{ collapsibleShowFunction: function($ul, complete) { $ul.slideDown(200, complete); }, collapsibleHideFunction: function($ul, complete) { $ul.slideUp(200, complete); } }"> ...
```

<br/>

> Btw,
> This free download button here isn't working. It has an PHP error.

Yep, thanks for this! This was caused by a recent bump to the PHP version running on the server and should be fixed now.

**Closed by vadikom** 2019-12-05 14:25 UTC
