### ISSUE TITLE
problem: combination of the Keyboard Addon and Bootstrap

### ISSUE THREAD

**Issue by eDitore** [vadikom/smartmenus#39] opened 2016-01-14 21:12 UTC
I’m building a site based on Bootstrap and using Smart Menu’s to control the main menu navigation. There is a problem with combination of the Keyboard Addon and Bootstrap  „down key” - it does not work in the second level and further levels. Is there any solution? Best regards.

**Comment by vadikom** [comment] 2016-01-15 11:32
I just tested in v1.0.0-beta1 (the last you can get from http://www.smartmenus.org/download/) and I can't reproduce the issue - down key works properly for all levels for me. Can you please post a demo?

**Comment by eDitore** [comment] 2016-01-15 16:11
Here is demo: https://jsfiddle.net/9qzv8ds4/6/ 
Start the keyboard navigation. Press only „down key” and you will see what is going to happen.

**Comment by vadikom** [comment] 2016-01-18 12:22
Thanks for taking the time to setup the demo, it really helped a lot!

It turned out it is an issue caused by a change introduced in Bootstrap 3.3.5. I have added a sample fix here:

https://jsfiddle.net/9qzv8ds4/7/

This should work for you for now. I would like to investigate the issue a bit more before implementing a generic workaround in the SmartMenus code but this will surely be fixed in v1.0.0 final.

Thanks again!

**Closed by vadikom** 2016-01-18 12:22 UTC
