### ISSUE TITLE
menu does not render childs at first time 

### ISSUE THREAD

**Issue by mmirzaeyan** [vadikom/smartmenus#133] opened 2020-12-03 17:21 UTC
Hi all 
I am using Smartmenus in an angular project and get the menu items from an API but for the first time the menu does not detect that there are children in the menu and does not show the arrows, but when I refresh the page it's fixed. 
the problem show after upgrade from 1.0.0 to the last version.
currently, I'm using the 1.1.0 version of Smartmenus with jquery 3.4.1 and angular 8

**Comment by vadikom** [comment] 2020-12-04 15:12
Hi, there shouldn't be any notable difference in the script init code between 1.1.1 and 1.0.0. I guess the issue is caused by some other changes in your own code but if you like, please post some kind of demo code since it's very hard to guess what might be the exact cause of the issue without looking at your code.

**Comment by mmirzaeyan** [comment] 2020-12-11 10:26
here is my Html code that render the view 

`<nav id="main-nav">
  <div class="toggle-nav">
    <i class="fa fa-bars sidebar-bar"></i>
  </div>
  
  <ul id="main-menu" class="sm pixelstrap sm-horizontal">
    
    <li>
      <div class="mobile-back text-right">
        بازگشت
          <i class="fa fa-angle-right pl-2" aria-hidden="true"></i>
      </div>
    </li>
    
    <li *ngFor="let menuItem of menuItems" [class]="menuItem.megaMenu ? 'mega' : ''">
        
        <a href="javascript:void(0)" *ngIf="menuItem.type === 'sub'">
           {{menuItem.title | translate}}
        </a>
        
        <a [routerLink]="!menuItem.type ? null : [menuItem.path]" *ngIf="menuItem.type === 'link'">
           {{menuItem.title | translate}}
        </a>
        
        <a href="{{ !menuItem.type ? null : menuItem.path }}" *ngIf="menuItem.type === 'extLink'">
           {{menuItem.title | translate}}
        </a>
        
        <a href="{{ !menuItem.type ? null : menuItem.path }}" *ngIf="menuItem.type === 'extTabLink'">
           {{menuItem.title | translate}}
        </a>
        

        
        <ul *ngIf="menuItem.children" [class]="menuItem.megaMenu && menuItem.megaMenuType == 'small' ? 'mega-menu feature-menu' : menuItem.megaMenuType == 'medium' ? 'mega-menu feature-menu product-menu' : menuItem.megaMenuType == 'large' ? 'mega-menu full-mega-menu center-mega-menu' : '' " [id]="'mega-menu'">
            
            <ng-container *ngIf="!menuItem.megaMenu">
              <li *ngFor="let childrenItem of menuItem.children">
                    
                    <a href="javascript:void(0)" *ngIf="childrenItem.type === 'sub'">
                       {{childrenItem.title | translate}}
                    </a>
                    
                    <a [routerLink]="!childrenItem.type ? null : [childrenItem.path]" *ngIf="childrenItem.type === 'link' && !menuItem.megaMenu">
                       {{childrenItem.title | translate}}
                    </a>
                    
                    <a href="{{ !childrenItem.type ? null : childrenItem.path }}" *ngIf="childrenItem.type === 'extLink' && !menuItem.megaMenu">
                       {{childrenItem.title | translate}}
                    </a>
                    
                    <a href="{{ !childrenItem.type ? null : childrenItem.path }}"  *ngIf="childrenItem.type === 'extTabLink' && !menuItem.megaMenu">
                       {{childrenItem.title | translate}}
                    </a>
                    
                    <ul *ngIf="childrenItem.children">
                      <li *ngFor="let childrenSubItem of childrenItem.children">
                          
                          <a [routerLink]="!childrenSubItem.type ? null : [childrenSubItem.path]" *ngIf="childrenSubItem.type === 'link' && !menuItem.megaMenu">
                             {{childrenSubItem.title | translate}}
                          </a>
                          
                          <a href="{{ !childrenSubItem.type ? null : childrenSubItem.path }}" *ngIf="childrenSubItem.type === 'extLink' && !menuItem.megaMenu">
                             {{childrenSubItem.title | translate}}
                          </a>
                          
                          <a href="{{ !childrenSubItem.type ? null : childrenSubItem.path }}"  *ngIf="childrenSubItem.type === 'extTabLink' && !menuItem.megaMenu">
                             {{childrenSubItem.title | translate}}
                          </a>
                      </li>
                    </ul>
              </li>
            </ng-container>
            
            
            <ng-container *ngIf="menuItem.megaMenu && menuItem.megaMenuType == 'small' || menuItem.megaMenuType == 'medium'">
            <li>
              <div class="container">
                <div class="row">
                  <div [class]="menuItem.megaMenuType == 'small' ? 'col-xl-4' : menuItem.megaMenuType == 'medium' ? 'col-xl-3' : '' " *ngFor="let childrenItem of menuItem.children">
                    
                    <a [routerLink]="!childrenItem.type ? null : [childrenItem.path]" *ngIf="childrenItem.type === 'link'">
                       <img [src]="childrenItem.image" alt="">
                       <h6>{{childrenItem.title | translate}}</h6>
                    </a>
                    
                    <a href="{{ !childrenItem.type ? null : childrenItem.path }}" *ngIf="childrenItem.type === 'extLink'">
                       <img [src]="childrenItem.image" alt="">
                       <h6>{{childrenItem.title | translate}}</h6>
                    </a>
                    
                    <a href="{{ !childrenItem.type ? null : childrenItem.path }}" target="_blank" *ngIf="childrenItem.type === 'extTabLink'">
                       <img [src]="childrenItem.image" alt="">
                       <h6>{{childrenItem.title | translate}}</h6>
                    </a>
                  </div>
                </div>
              </div>
            </li>
            </ng-container>
            
            
            <ng-container *ngIf="menuItem.megaMenu && menuItem.megaMenuType == 'large'">
            <li>
              <div class="container">
                <div class="row">
                  <div class="col mega-box" *ngFor="let childrenItem of menuItem.children">
                    <div class="link-section">
                      <div class="menu-title">
                        <h5>{{childrenItem.title | translate}}</h5>
                      </div>
                      <div class="menu-content">
                        
                        <ul>
                          <li *ngFor="let childrenSubItem of childrenItem.children">
                            
                            <a [routerLink]="!childrenSubItem.type ? null : [childrenSubItem.path]">
                               {{childrenSubItem.title }}
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            </ng-container>
            
        </ul>
    </li>

  </ul>
</nav>
`

and in the component because of that the data structure that i get from API was diffrent i changed it like this : 

`import {Component, OnInit} from '@angular/core';
import {Menu} from './navbar-items';
import {NavbarService} from './navbar.service';

declare var $: any;

@Component({
    selector: 'multikart-navbar',
    templateUrl: './multikart-navbar.component.html'
})
export class MultiKartNavbarComponent implements OnInit {

    public menuItems: Menu[];

    constructor(private navbarService: NavbarService) {
        this.menuItems = [];
        this.navbarService.getAll().subscribe((menuResponse) => {
            const levelOne = menuResponse.filter(
                menu => menu.parentId === '47082fa4-596a-11ea-b2f9-d4eb1fd7dabe');
            levelOne.forEach((one) => {
                let menuItem: Menu = new Menu();
                menuItem.title = one.title;
                menuItem.type = 'sub';
                if (one.menuTypeTitle != null && one.menuTypeTitle != 'simple') {
                    menuItem.megaMenu = true;
                    menuItem.megaMenuType = one.menuTypeTitle;
                }
                if (one.items.length > 0) {
                    let children: Menu[] = [];
                    one.items.forEach((two) => {
                        let menuItem2: Menu = new Menu();
                        menuItem2.title = two.title;
                        if (one.menuTypeTitle == 'simple')
                            menuItem2.type = 'extTabLink';
                        else
                            menuItem2.type = 'link';
                        menuItem2.path = '/#/products/' + two.id;
                        if (two.items.length > 0) {
                            let children2: Menu[] = [];
                            two.items.forEach((three) => {
                                let menuItem3: Menu = new Menu();
                                menuItem3.title = three.title;
                                if (one.menuTypeTitle == 'simple')
                                    menuItem3.type = 'extTabLink';
                                else
                                    menuItem3.type = 'link';
                                menuItem3.type = 'link';
                                menuItem3.path = '/products/' + three.id;
                                children2.push(menuItem3);
                                if (three.items.length > 0) {
                                    let children3: Menu[] = [];
                                    three.items.forEach((four) => {
                                        let menuItem4: Menu = new Menu();
                                        menuItem4.title = four.title;
                                        if (one.menuTypeTitle == 'simple')
                                            menuItem4.type = 'extTabLink';
                                        else
                                            menuItem4.type = 'link';
                                        menuItem4.type = 'link';
                                        menuItem4.path = '/products/' + four.id;
                                        children3.push(menuItem4);

                                    });
                                    menuItem3.children = children3;
                                }
                            });
                            menuItem2.children = children2;
                        }
                        children.push(menuItem2);
                    });

                    menuItem.children = children;
                }
                this.menuItems.push(menuItem);
            })

        });
    }

    ngOnInit() {

        //this.menuItems = MENUITEMS.filter(menuItem => menuItem);
    }

}
`

**Comment by mmirzaeyan** [comment] 2020-12-12 16:08
> Hi, there shouldn't be any notable difference in the script init code between 1.1.1 and 1.0.0. I guess the issue is caused by some other changes in your own code but if you like, please post some kind of demo code since it's very hard to guess what might be the exact cause of the issue without looking at your code.

i think it's a bug in css section that not detect nodes has child.

**Comment by vadikom** [comment] 2020-12-17 16:02
The CSS shouldn't affect the way the script detects and initializes any sub menus so it's most probably not related to CSS at all.

Unfortunately, the code samples you've posted don't give me any clue why the sub menus are not properly initialized on page load but work fine on reload. Could you please post a link to some kind of demo instead?

**Comment by mmirzaeyan** [comment] 2020-12-21 19:58
kotobz.com

**Comment by vadikom** [comment] 2020-12-22 17:49
OK, thanks for the complete demo!

I am still not able to edit and test your code but I believe I have an idea what's wrong. You have your menu init code in a separate file:

https://kotobz.com/assets/multikart/js/menu.js

with contents:

```javascript
"use strict";
$(document).ready(function() {
  $('#main-menu').smartmenus({
      subMenusSubOffsetX: 1,
      subMenusSubOffsetY: -8
  });
  $('#sub-menu').smartmenus({
      subMenusSubOffsetX: 1,
      subMenusSubOffsetY: -8
  })
});
```

and it is called like "normally" when the global onDomReady event is fired. However, due to the fact that you are using an Angular component to build your menu, I guess sometimes the onDomReady event is fired before Angular has managed to generate your menu structure.

So I would suggest, removing/disabling the above code and instead putting the init code you need inside the `ngOnInit` method in your Angular menu component - e.g. if jQuery is configured properly to be used inside your Angular component (which looks like it from the code sample you posted but again, I am not able to test and confirm this) something like this should solve the menu init issue:

```javascript
import {Component, OnInit} from '@angular/core';
import {Menu} from './navbar-items';
import {NavbarService} from './navbar.service';

declare var $: any;

@Component({
    selector: 'multikart-navbar',
    templateUrl: './multikart-navbar.component.html'
})
export class MultiKartNavbarComponent implements OnInit {

    public menuItems: Menu[];

    constructor(private navbarService: NavbarService) {
        this.menuItems = [];
        this.navbarService.getAll().subscribe((menuResponse) => {
            const levelOne = menuResponse.filter(
                menu => menu.parentId === '47082fa4-596a-11ea-b2f9-d4eb1fd7dabe');
            levelOne.forEach((one) => {
                let menuItem: Menu = new Menu();
                menuItem.title = one.title;
                menuItem.type = 'sub';
                if (one.menuTypeTitle != null && one.menuTypeTitle != 'simple') {
                    menuItem.megaMenu = true;
                    menuItem.megaMenuType = one.menuTypeTitle;
                }
                if (one.items.length > 0) {
                    let children: Menu[] = [];
                    one.items.forEach((two) => {
                        let menuItem2: Menu = new Menu();
                        menuItem2.title = two.title;
                        if (one.menuTypeTitle == 'simple')
                            menuItem2.type = 'extTabLink';
                        else
                            menuItem2.type = 'link';
                        menuItem2.path = '/#/products/' + two.id;
                        if (two.items.length > 0) {
                            let children2: Menu[] = [];
                            two.items.forEach((three) => {
                                let menuItem3: Menu = new Menu();
                                menuItem3.title = three.title;
                                if (one.menuTypeTitle == 'simple')
                                    menuItem3.type = 'extTabLink';
                                else
                                    menuItem3.type = 'link';
                                menuItem3.type = 'link';
                                menuItem3.path = '/products/' + three.id;
                                children2.push(menuItem3);
                                if (three.items.length > 0) {
                                    let children3: Menu[] = [];
                                    three.items.forEach((four) => {
                                        let menuItem4: Menu = new Menu();
                                        menuItem4.title = four.title;
                                        if (one.menuTypeTitle == 'simple')
                                            menuItem4.type = 'extTabLink';
                                        else
                                            menuItem4.type = 'link';
                                        menuItem4.type = 'link';
                                        menuItem4.path = '/products/' + four.id;
                                        children3.push(menuItem4);

                                    });
                                    menuItem3.children = children3;
                                }
                            });
                            menuItem2.children = children2;
                        }
                        children.push(menuItem2);
                    });

                    menuItem.children = children;
                }
                this.menuItems.push(menuItem);
            })

        });
    }

    ngOnInit() {

      // SmartMenus jQuery init
      $('#main-menu').smartmenus({
          subMenusSubOffsetX: 1,
          subMenusSubOffsetY: -8
      });

    }

}
```

BTW, please note that I normally use the GitHub Issues page for bugs only and this basically turned into a support issue so I will close it now. In the future please post similar support queries in the [community forums](https://www.smartmenus.org/forums/) (for free support) or you could also sign up for [premium support](https://www.smartmenus.org/support/premium-support/) if needed.

I hope this help! Cheers!

**Closed by vadikom** 2020-12-22 17:49 UTC
